config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#index'
  get '/dashboard', to: 'users#dashboard'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'register'},
              controllers: { omniauth_callbacks: 'omniauth_callbacks',registrations: 'registrations'}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one_attached :avatar
  has_many :gigs

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20] # this creates a random password
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.uid = auth.uid
        user.provider = auth.provider

        #user.skip_confirmation!

      end
    end
  end

  # def hidden_phone
  #   if self.phone && self.phone.length > 3
  #     "*" * (self.phone.length - 3) + self.phone.last(3)
  #   end
  # end
end

# def self.from_omniauth(access_token)
# data = access_token.info
# user = User.where(email: data['email']).first

# # Uncomment the section below if you want users to be created if they don't exist
# unless user
#     user = User.create(name: data['name'],
#        email: data['email'],
#        password: Devise.friendly_token[0,20]
#     )
# end
# user
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/dashboard.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns">
      <!-- LEFT SIDE -->
      <div class="column is-one-third">
        <div class="columns is-multiline">
          <!-- Top Card -->
          <div class="column is-full">
            <div class="card">
              <!-- Avatar -->
              <div class="card-content is-horizontal-center is-flex">
                <figure class="image is-128x128">
                  <%= image_tag avatar_url(current_user), class: 'is-rounded'%>
                </figure>
              </div>
              <div class="card-content">
                <!-- Upload Button -->
                <div class="content has-text-centered">
                  <p class="title is-5"><%= current_user.full_name %></p>
                  <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post   do |f| %>
                    <div class="file">
                      <label  class="button is-primary is-outlined is-fullwidth">
                        <%= f.file_field :avatar, class: "file-input", onchange: "this.form.submit()"%>
                        <i class="fas fa-upload"></i> &nbsp;&nbsp;&nbsp; Upload Avatar
                      </label>
                    </div>
                  <% end %>
                </div>
                <hr class="h-10">
                <!-- Member -->
                <article class="media">
                  <div class="media-content">Member since</div>
                  <div class="media-right">
                    <strong><%= current_user.created_at.strftime('%b %Y')%></strong>
                  </div>
                </article>
                <hr class="h-10">
                <!-- From -->
                <article>
                  <div class="media">
                    <div class="media-content">From</div>
                    <div class="media-right">
                      <strong><%= current_user.from%></strong><i class="toggle far fa-edit" aria-controls="user-from"></i>
                    </div>
                  </div>
                  <div class="content">
                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-from', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_field :from, autofocus: true, autocomplete: 'form' , class: 'input'%>
                      </div>
                      <a class="toggle button is-light" aria-controls="user-from">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">
                <!-- Online Status -->
                <article>
                  <div class="media">
                    <div class="media-content">Online Status</div>
                    <div class="media-right">
                      <strong><%if current_user.status%> Online<%else%> Offline<%end%></strong><i class="toggle far fa-edit" aria-controls="user-status"></i>
                    </div>
                  </div>
                  <div class="content">
                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-status', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.select(:status, options_for_select([["Online", true], ["Offline", false]]), {}, {class: "select is-fullwidth"} )%>
                      </div>
                      <a  class="toggle button is-light" aria-controls="user-status">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>

                <!-- Subscription Status -->
                <% if @subscription.present? %>
                    <hr class="h-10">
                <article>
                  <div class="media">
                    <div class="media-content">Subscription</div>
                    <div class="media-right">
                      <strong></strong><i class="toggle far fa-edit" aria-controls="user-subscription"></i>
                    </div>
                  </div>
                  <div class="content">
                  </div>
                </article>
                <%end %>
                
              </div>
            </div>
          </div>
          <!-- Bottom Card -->
          <div class="column is-full">
            <div class="card">
              <div class="card-content">
                <!-- About -->
                <article>
                  <div class="media">
                    <div class="media-content">
                      <p>
                        <strong> About Yourself</strong>
                        <br />
                        <%= current_user.about %>
                      </p>
                    </div>
                    <div class="media-right">
                      <i class="toggle far fa-edit" aria-controls="user-about"></i>
                    </div>
                  </div>
                  <div class="content">
                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-about', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_area :about, autofocus: true, autocomplete: 'form' , class: 'input'%>
                      </div>
                      <a  class="toggle button is-light" aria-controls="user-about">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">
                <!-- Language -->
                <article>
                  <div class="media">
                    <div class="media-content">
                      <p>
                        <strong> Language</strong>
                        <br />
                        <%= current_user.language %>
                      </p>
                    </div>
                    <div class="media-right">
                      <i class="toggle far fa-edit" aria-controls="user-language"></i>
                    </div>
                  </div>
                  <div class="content">
                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-language', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_field :language, autofocus: true, autocomplete: 'form' , class: 'input'%>
                      </div>
                      <a  class="toggle button is-light" aria-controls="user-language">Cancel</a>
                      <%= f.submit "Save", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">
                <!-- Linked Account -->
                <article class="media">
                  <div class="content">
                    <p>
                      <strong> Linked Account</strong><br />
                      <% if current_user.uid %>
                        <span class="has-text-success">Google verified</span>
                      <% else %>
                        <%= button_to 'Connect to Google', user_google_oauth2_omniauth_authorize_path , class: "has-text-danger"%>
                      <% end %>
                    </p>
                  </div>
                </article>
                <!--Mobile Number -->
                <article>
                  <div class="media">
                    <div class="media-content">
                      <p>
                        <strong> Mobile Number </strong>
                        <br />
                        <%# <%= current_user.hidden_phone %> 
                      </p>
                    </div>
                    <div class="media-right">
                      <i class="toggle far fa-edit" aria-controls="user-phone"></i>
                    </div>
                  </div>
                  <div class="content">
                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-phone', class: 'is-hidden'} do |f| %>
                      <div class="field">
                        <%= f.text_field :about, autofocus: true, autocomplete: 'form' , class: 'input', id: 'phone_number' %>
                      </div>
                      <a  class="toggle button is-light" aria-controls="user-phone">Cancel</a>
                      <%= link_to 'Add & Verify', "javascript:verifyPhone()", class: "button is-danger" %>
                    <% end %>
                  </div>
                </article>
                
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- RIGHT SIDE -->
      <div class="column">
        <div class="columns is-multiline">
          <!-- Create New Gig -->
          <div class="column is-one-third has-text-centered">
            <%# <%= link_to new_gig_path do %> 
              <div class="card">
                <div class="card-image card-content is-horizontal-center is-flex ">
                  <figure class="image is-128x128 ">
                    <!-- Plus Icon Here -->
                    <%= image_tag 'icon_add.png'%>
                  </figure>
                </div>
                <div class="card-content">
                  <strong>Create a new gig</strong>
                </div>
              </div>
            <%# <% end %> 
          </div>
          <!-- Sample Gig -->
          
            <div class="column is-one-third">
              <div class="card">
                <div class="card-image">
                
                </div>
                <div class="card-content p-t-5 p-b-5">
                  <p class="subtitle is-6 m-b-5"></p>
                  <span class="star-review"><i class="fa fa-star"></i>
                   
                  </span>
                </div>
                <footer class="card-footer">
                  <%# <% basic_price = gig.pricings.find{ |p| p.pricing_type == 'basic'} %> 
                  <a class="has-text-danger is-block card-footer-item has-text-right">
                    
                      <span class="small-title">STARTING AT</span>
                      <%# <strong>$<%= basic_price.price </strong> %>
                  </a>
                </footer>
              </div>
            </div>
         
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>