config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#index'
  get '/dashboard', to: 'users#dashboard'

  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'register'},
              controllers: { omniauth_callbacks: 'omniauth_callbacks',registrations: 'registrations'}

end

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
  <div class="container">
    <div class="navbar">
      <% @categories.each do |item| %>
        <%= link_to "#{item.name}", search_path(category: item.id), class: "navbar-item" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_gigs.html.erb
<% @gigs.each do |gig| %>
  <div class="column is-one-third">
    <div class="card">
      <div class="card-image">
        <%= link_to gig_path(gig) do %>
          <figure class="image is-4by3">
            <!-- Gig Cover Image Here -->
            <%= image_tag gig_cover(gig) %>
          </figure>
        <% end %>
      </div>
      <div class="card-content p-t-5 p-b-5">
        <p class="subtitle is-6 m-b-5"><%= link_to gig.title.truncate(20), gig_path(gig) %></p>
        <span class="star-review"><i class="fa fa-star"></i>
          <%= gig.average_rating %> <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
        </span>
      </div>
      <footer class="card-footer">
        <span class="card-footer-item">
          <%= link_to users_path(gig.user) do %>
            <figure class="image is-32x32">
              <%= image_tag avatar_url(gig.user), class: "is-rounded" %>
            </figure>
          <% end %>
        </span>
        <a class="has-text-danger is-block card-footer-item has-text-right">
          <span class="small-title">STARTING AT</span>
          <strong>$<%= gig.price %></strong>
        </a>
      </footer>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-dark is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <h1 class="title is-size-4 has-text-white"><strong>ASON</strong></h1>
    </a>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= form_tag dashboard_path, method: :get do %>
        <div class="field has-addons <%= 'is-hidden' if current_page?(root_path)%>">
        <div class="control has-icons-left">
          <span class="icon is-small is-left">
            <i class="fa fa-search"></i>
          </span>
          <%=  text_field_tag 'q', '',  class: "input", placeholder: "Try 'data analysis'" %>
        </div>
        <div class="control">
          <button class="button is-danger" type="Submit">Search</button>
        </div>
        </div>
      <% end %>
      </div>
    </div>
    <div class="navbar-end">
    <%= link_to "Pricing", dashboard_path,class: "navbar-item" %>
     <%= link_to "Post Gig", dashboard_path,class: "navbar-item" %>
      <%= link_to "Browse Gig", dashboard_path,class: "navbar-item" %>
      <% if (!user_signed_in?) %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to 'Sign Up', new_user_registration_path, class: "button is-primary" %>
            <%= link_to 'Login ', new_user_session_path, class: "button is-light" %>
          </div>
        </div>
      <% else %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a  class="navbar-link">
            <figure class="image is-24x24 m-r-5 avatar<%= current_user.status ? "online" : "offline" %>">
              <%= image_tag avatar_url(current_user), class: 'is-rounded'%>
            </figure>
            <%= current_user.full_name %>
          </a>

          <div class="navbar-dropdown">
            <%= link_to 'Profile ', edit_user_registration_path, class: "navbar-item" %>
             <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
            <hr class="navbar-divider">
            <%= link_to 'Logout ', destroy_user_session_path, method: :delete, class: "navbar-item" %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>
</div>
</nav>




<script>
  $(document).ready(function() {
  
    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
  
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        $(".navbar-burger").toggleClass("is-active");
        $(".navbar-menu").toggleClass("is-active");
  
    });
  });
</script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
<script type = "text/javascript">
    <% flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
    toastr['<%= type %>']('<%= value %>')
    <% end %>
</script>

<% end %>



<!--<% unless flash.empty? %>
  <script>
    <%flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success')%>
      new Noty({
        type: '<%= type %>',
        layout: 'topRight',
         timeout: '3000',
         theme: 'sunset',
         text: '<%= value %>'
      }).show();
    <% end %>

  </script>
<% end %>-->